import React, { ReactNode } from "react";
import type { Metadata } from "next";
import Footer from "~/components/Footer";

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

type Props = {
    children: ReactNode;
};
const PublicLayout = function ({ children }: Readonly<Props>) {
    return (
        <div>
            <main>{children}</main>
            <Footer />
        </div>
    );
};

export default PublicLayout;
