import { images } from "~/public/images";

export const projects = [
  {
    id: "1",
    title: "Beyond Financial Sovereignty: Democratizing Treasury Administration",
    image: images.landing01,
    date: "2025-07-14",
    author: "James Dunseith",
    action: "Blog Post",
    slug: "beyond-financial-sovereignty",
    excerpt: "Explore how decentralized treasury tools are reshaping the way DAOs manage capital and make collaborative decisions.",
  },
  {
    id: "2",
    title: "The Future of On-Chain Governance: Risks & Opportunities",
    image: images.landing02,
    date: "2025-07-10",
    author: "Mira Chan",
    action: "Blog Post",
    slug: "onchain-governance-risks-opportunities",
    excerpt: "An in-depth look at the growing field of on-chain governance, and what it means for transparency, accountability, and voter fatigue.",
  },
  {
    id: "3",
    title: "Treasury Diversification in Volatile Markets",
    image: images.landing03,
    date: "2025-06-28",
    author: "Luis Fernandez",
    action: "Blog Post",
    slug: "treasury-diversification-strategies",
    excerpt: "Discover strategies DAOs are using to protect their treasuries during turbulent market cycles without compromising decentralization.",
  },
  {
    id: "4",
    title: "Designing Incentive Systems That Actually Work",
    image: images.landing04,
    date: "2025-06-15",
    author: "Emily Hart",
    action: "Blog Post",
    slug: "dao-incentive-mechanisms",
    excerpt: "A practical guide to creating fair and effective incentive systems for contributors in decentralized organizations.",
  },
  {
    id: "5",
    title: "Multi-Sig vs Smart Contract: Choosing the Right DAO Treasury Stack",
    image: images.landing01,
    date: "2025-05-30",
    author: "Keiran Patel",
    action: "Blog Post",
    slug: "multisig-vs-smart-contract",
    excerpt: "Understand the pros and cons of different treasury control mechanisms, from classic multisigs to advanced programmable contracts.",
  },
];
